[IT-1681] Delete dependent domain objects in geb spec
I am currently getting the following exception with Grails 3.3.2 when
JobListGebSpec is executed:
org.h2.jdbc.JdbcSQLException: Referential integrity constraint violation: "FK9E05EADFBD7A3DD2: PUBLIC.JOB_RESULT FOREIGN KEY(JOB_ID) REFERENCES PUBLIC.JOB(ID) (6)";
In Grails 3.1.5, the transaction would finish without throwing an
exception but afterwards the Job entities would still persist in the
database. I believe this is because org.h2.jdbc.JdbcSQLException is
a checked exception (i.e. one that does not extend RuntimeException)
and these did not roll back transactions before GORM 6, as described
in the warning box here:
http://docs.grails.org/3.3.2/guide/single.html#_declarative_transactions