[IT-1681] Add empty index.gsp
Both index.gsp files will never be displayed to the user because both
corresponding controllers redirect from the index page to the create
action. But for some reason, in the new Grails version, there is the
following exception being thrown if these index files don't exist:
javax.servlet.ServletException: Could not resolve view with name 'index' in servlet with name 'grailsDispatcherServlet'