[IT-1681] Fix integration test
Before this change, the integration test failed with the exception:
org.hibernate.HibernateException: A collection with cascade="all-delete-orphan" was no longer referenced by the owning entity instance: de.iteratec.osm.csi.CsiConfiguration.timeToCsMappings
So I guess the build-test-data plugin already created child objects
of csiConfiguration and we shouldn't overwrite them with new ones.